#!/bin/sh -ue

# This script installs Nix package manager inside a Termux installation.
# Copyright (c) 2019 Alexander Sosedkin <monk@unboiled.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Based off the official Nix install script (https://nixos.org/nix/install),
# presumably written by Eelco Dolstra.


# This script installs Nix package manager inside a Termux installation.
# It does not require root, user namespaces or disabling SELinux,
# but it relies on proot and numerous hacks instead.
# Only tested with aarch64, may also accidentally work on x86.

# Usage:
# * Install and run Termux
# * Execute this script inside Termux

# Careful, this is carelessly written alpha-quality stuff.


PLAYGROUND="$HOME/.nix"
DIVE_SCRIPT="$PLAYGROUND/nix-powered"
TERMUX_BIN="/data/data/com.termux/files/usr/bin"



oops() {
    echo "$0:" "$@" >&2
    exit 1
}


if [ ! -x "$DIVE_SCRIPT" ]; then
	echo "removing the previous installation..."
	chmod -R 700 "$PLAYGROUND" || true
	rm -rf "$PLAYGROUND" || oops "failed to remove $PLAYGROUND"
	mkdir -p "$PLAYGROUND" || oops "failed to create $PLAYGROUND"

	echo "installing tools..."
	pkg install -y proot bzip2 tar wget || oops "failed to install required tools"

	tmpDir="$PLAYGROUND/tmp"
	mkdir -p "$tmpDir" || oops "false to create $tmpDir"

	echo "preparing mock /nix and /etc..."
	mkdir "$PLAYGROUND/nix" || oops "failed to create $PLAYGROUND/nix"
	mkdir "$PLAYGROUND/etc" || oops "failed to create $PLAYGROUND/etc"
	echo 'nameserver 1.1.1.1' > "$PLAYGROUND/etc/resolv.conf" || oops "failed to create $PLAYGROUND/etc/resolv.conf"
	mkdir "$PLAYGROUND/etc/nix/" || oops "failed to create $PLAYGROUND/etc/nix"
	# https://github.com/NixOS/nix/issues/2632#issuecomment-457610729
	echo 'sandbox = false' > "$PLAYGROUND/etc/nix/nix.conf" || oops "failed to create $PLAYGROUND/etc/nix/nix.conf"

	case "$(uname -s).$(uname -m)" in
		Linux.x86_64)
			hash=afa6bf82bacb18ec0d6a1fd992b718192f895023d6cea8b94b2fb35fce352ff5
			path=1sh0llzrvkah17hypza89fcd5bmm35cl/nix-2.13.3-x86_64-linux.tar.xz
			system=x86_64-linux
			;;
		Linux.i?86)
			hash=579a79a155c93c07f23e58de1dfa766d905239315b6b8c116e0ad7ffb7b14135
			path=bg4vn61787q0l6wny81laa7al4sw5hda/nix-2.13.3-i686-linux.tar.xz
			system=i686-linux
			;;
		Linux.aarch64)
			hash=dfbbaa86404c3efe74d87c8d4c39081affc673c8b5f64cfefc4ab0eaf84ed39b
			path=zdq06xpx6a4a1hkaqcvjj9lbd7vqd9c3/nix-2.13.3-aarch64-linux.tar.xz
			system=aarch64-linux
			;;
		Linux.armv6l)
			hash=debcb8a09744e83fca06efc6c5eee3f6066653da27dda8e0fb861e565b93f5f5
			path=60gh3w8ikkhf547d3scyhsn7xlpp1k01/nix-2.13.3-armv6l-linux.tar.xz
			system=armv6l-linux
			;;
		Linux.armv7l)
			hash=07a1e718e9ebfd11b0c8ba947029b5dc50a81f4e6f8ac5b8b8e3572e1ce436cb
			path=cr6g8xc66yc02avw3ih4h96dbamqc3xw/nix-2.13.3-armv7l-linux.tar.xz
			system=armv7l-linux
			;;
		Darwin.x86_64)
			hash=2b036faeccdce4b6ba9ca4aa7971b49d13a1ee4ac13ea834fb24c4d0d7e8536a
			path=s8yj3dnxmkk8ggzzymxwm1qb3s5hk133/nix-2.13.3-x86_64-darwin.tar.xz
			system=x86_64-darwin
			;;
		Darwin.arm64|Darwin.aarch64)
			hash=200e777b541ddbadafdbe3817dba504754fa8fb0c9d1dd3f33dee6578045ab39
			path=nh14dgrnxgd9dgg14bvbmi33dd5ipnml/nix-2.13.3-aarch64-darwin.tar.xz
			system=aarch64-darwin
			;;
		*) oops "sorry, there is no binary distribution of Nix for your platform";;
	esac

	url=https://releases.nixos.org/nix/nix-2.13.3/nix-2.13.3-$system.tar.xz

	tarball=$tmpDir/nix-2.13.3-$system.tar.xz

	echo "downloading Nix 2.2.1 binary tarball for $system from '$url' to '$tmpDir'..."
	$TERMUX_BIN/wget "$url" -O "$tarball" || oops "failed to download '$url'"

	hash2="$(sha256sum -b "$tarball" | cut -c1-64)"

	if [ "$hash" != "$hash2" ]; then
		oops "SHA-256 hash mismatch in '$url'; expected $hash, got $hash2"
	fi

	echo "unpacking $tarball..."
	unpack=$tmpDir/unpack
	mkdir -p "$unpack"
	cleanup() {
		rm -rf "$unpack"
	}
	trap cleanup EXIT INT QUIT TERM
	< "$tarball" xzcat | $TERMUX_BIN/tar -xf - -C "$unpack" || oops "failed to unpack $tarball"

	script=$(echo "$unpack"/*/install)

	[ -e "$script" ] || oops "installation script is missing from the binary tarball!"

	INTERMEDIATE_SCRIPT="$tmpDir/intermediate_install_script"
	{
########
	cat > "$INTERMEDIATE_SCRIPT" << --------EOF
	export USER=\$(whoami)
	export NIX_INSTALLER_NO_MODIFY_PROFILE=true
	unset LD_LIBRARY_PATH
	unset LD_PRELOAD
	$script "\$@"
--------EOF
	} || oops "failed to create $INTERMEDIATE_SCRIPT"

	chmod +x "$INTERMEDIATE_SCRIPT" || oops "failed to chmod +x $INTERMEDIATE_SCRIPT"

	echo "running Nix install script in proot..."
	proot \
		-b "$PLAYGROUND/nix:/nix" \
		-b "$PLAYGROUND/etc:/etc" \
		--link2symlink \
		"$INTERMEDIATE_SCRIPT" || oops "failed to run Nix install script in proot"

	echo "creating $DIVE_SCRIPT and finalizing the installation..."
	{
########
	cat > "$DIVE_SCRIPT" << --------EOF
	#!/bin/sh -e
	export PS1="nix-powered> "
	export USER=$(whoami)
	unset LD_LIBRARY_PATH
	unset LD_PRELOAD
	echo Termux PATH \$PATH
	TERMUX_PATH="\$PATH"
	. \$HOME/.nix-profile/etc/profile.d/nix.sh
	export PATH=\${PATH%":\$TERMUX_PATH"}
	"\$@"
--------EOF
	} || oops "failed to create $DIVE_SCRIPT"
	chmod +x "$DIVE_SCRIPT" || oops "failed to chmod +x $DIVE_SCRIPT"

	echo "installation is completed."

	echo "to reinstall, rm -r \"$PLAYGROUND\" and re-run the script"
fi


proot \
	-b "$PLAYGROUND/nix:/nix" \
	-b "$PLAYGROUND/etc:/etc" \
	-b "/etc:/android-etc" \
	--link2symlink \
	"$DIVE_SCRIPT" "$@"
